var terminals = 
[{"parent_station":"place-lake","stop_id":70106,"stop_name":"Boston College - Inbound","direction_id":1},
{"parent_station":"place-lake","stop_id":70107,"stop_name":"Boston College - Outbound","direction_id":0},
{"parent_station":"place-river","stop_id":70160,"stop_name":"Riverside - Inbound","direction_id":1},
{"parent_station":"place-river","stop_id":70161,"stop_name":"Riverside - Outbound","direction_id":0},
{"parent_station":"place-clmnl","stop_id":70237,"stop_name":"Cleveland Circle - Outbound","direction_id":0},
{"parent_station":"place-clmnl","stop_id":70238,"stop_name":"Cleveland Circle - Inbound","direction_id":1},
{"parent_station":"place-hsmnl","stop_id":70259,"stop_name":"Heath Street - Outbound","direction_id":0},
{"parent_station":"place-hsmnl","stop_id":70260,"stop_name":"Heath Street - Inbound","direction_id":1},
{"parent_station":"place-lech","stop_id":70209,"stop_name":"Lechmere - Outbound","direction_id":1},
{"parent_station":"place-lech","stop_id":70210,"stop_name":"Lechmere - Inbound","direction_id":0},
{"parent_station":"place-prktrm","stop_id":70196,"stop_name":"Park Street - Green Line - B Branch Berth","direction_id":0},
{"parent_station":"place-prktrm","stop_id":70197,"stop_name":"Park Street - Green Line - C Branch Berth","direction_id":0},
{"parent_station":"place-prktrm","stop_id":70198,"stop_name":"Park Street - Green Line - D Branch Berth","direction_id":0},
{"parent_station":"place-prktrm","stop_id":70199,"stop_name":"Park Street - Green Line - E Branch Berth","direction_id":0},
{"parent_station":"place-prktrm","stop_id":70200,"stop_name":"Park Street - Green Line Eastbound","direction_id":1},
{"parent_station":"place-gover","stop_id":70201,"stop_name":"Government Center - Green Line Eastbound","direction_id":1},
{"parent_station":"place-gover","stop_id":70202,"stop_name":"Government Center - Green Line Westbound","direction_id":0},
{"parent_station":"place-north","stop_id":70205,"stop_name":"North Station - Green Line Outbound","direction_id":1},
{"parent_station":"place-north","stop_id":70206,"stop_name":"North Station - Green Line Inbound","direction_id":0}]